version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "5173:80"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro  #인증서 마운트
    networks:
      - app-network

networks:
  app-network:
    driver: bridge